 print("Hello world")
name=input("what is your name")
age=int(input("what is your age"))
surname=input("what is your surname")
print(name,age,surname)
fathername=input("what is your fathername")
mothername=input("what is your mothername")
Adharnumber=int(input("enter your adharnumber"))
print(fathername,mothername,Adharnumber)
address=input("enter your address")
pancard=input("enter your pancard details")
collegename=input("enter your collegename")
print(address,pancard,collegename)
collegeaddress=input("enter your collegeaddress")
pincode=input("enter your pincode")
coursename=input("enter your coursename")
print(pincode,coursename)
tc_number=int(input("enter your tc number"))
phonenumber=int(input("enter your phone number"))
stsemesterpercentage=input("enter your 1st semester percentage")
semesterpercentage=input("enter your 2nd semester percentage")
print(tc_number,phonenumber,stsemesterpercentage,semesterpercentage)
englishmark=int(input("enter your englishmark"))
pythonmark=int(input("enter your python mark"))
datastructuremark=int(input("enter your datastructuremark"))
totalmark=int(input("enter your total mark"))
rollnumber=int(input("enter your roll number"))
print(englishmark,pythonmark,datastructuremark,totalmark,rollnumber )


